name: My First Workflow # 1. 워크플로우 이름

on: [push] # 2. 이벤트: 코드가 push 될 때 실행

jobs:
  say-hello: # 3. Job 식별자 (이름)
    runs-on: ubuntu-latest # 4. 러너: 최신 우분투 환경에서 실행
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 5. 액션 사용: 내 코드를 가져옴
      
      - name: Print Hello
        run: echo "Hello, GitHub Actions!" # 6. 쉘 명령어 실행
        
      - name: Check files
        run: ls -la # 현재 폴더 파일 목록 확인
