name: Build and Push Docker Image

on:
  push:
    branches: [ "develop" ]  # develop 브랜치에 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      working-directory: apps/server # 폴더 경로 명시
      run: ./gradlew build -x test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: apps/server # Docker 컨텍스트를 하위 폴더로 지정
        file: apps/server/Dockerfile # Dockerfile 위치 명시
        push: true
        tags: bbumbbum/ddubuk:latest
